# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "92b3aa8408bd0a328a21bef72b9f7bec"
name = "acuotaz-widgets"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
handle = "acuotaz-widgets-extension"

[build]

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
